
      { 0x0000 ,  0x0000,
        "Reserved -  - Reserved"
      },
      { 0x0010 ,  0x0017,
        "ASTRA -  - SES ASTRA"
      },
      { 0x0018 ,  0x0018,
        "ICO B1 -  - ICO Satellite Services G.P."
      },
      { 0x0019 ,  0x0019,
        "ICO B2 -  - ICO Satellite Services G.P."
      },
      { 0x0020 ,  0x0020,
        "Sogecable -  - Sogecable S.A."
      },
      { 0x0021 ,  0x0021,
        "Sogecable 2 -  - Sogecable S.A."
      },
      { 0x0022 ,  0x0022,
        "Sogecable TDT -  - Sogecable S.A."
      },
      { 0x002F ,  0x002F,
        "TVNZ Digital -  - TNVZ  "
      },
      { 0x0030 ,  0x0030,
        "TT Data Services -  - TechnoTrend Görler GmbH"
      },
      { 0x0031 ,  0x0031,
        "Balon -  - Interactive Technologies PLC"
      },
      { 0x006E ,  0x006E,
        "Europe Online Networks (EON) -  - Europe Online Networks S.A  "
      },
      { 0x006F ,  0x006F,
        "WRN D-Radiosat -  - WRN (World Radio Network )"
      },
      { 0x0070 ,  0x007F,
        "Eutelsat Satellite System n° 1 - n° 16 -  - EUTELSAT – European Telecommunications Satellite Organization "
      },
      { 0x0080 ,  0x0080,
        "Digital Platform DIGITURK1 -  - Digital Platform  "
      },
      { 0x0081 ,  0x0081,
        "TV Polsat -  - Telewizja Polsat  "
      },
      { 0x0082 ,  0x0082,
        "TV Cabo Portugal -  - TV Cabo Portugal  "
      },
      { 0x0083 ,  0x0083,
        "Dijital Yayýn Pazarlama ve Ticaret A.Þ. -  - Dijital Yayýn Pazarlama ve Ticaret A.Þ ."
      },
      { 0x0084 ,  0x0084,
        "Digital Platform DIGITURK2 -  - DIGITURK"
      },
      { 0x0085 ,  0x0085,
        "RTV38 -  - RTV38 spa"
      },
      { 0x0086 ,  0x0086,
        "TV Numeric -  - LogiWays"
      },
      { 0x0087 ,  0x0087,
        "Vision TV -  - SES-Sirius"
      },
      { 0x0088 ,  0x0088,
        "VisionTV -  - VisionTV LLC"
      },
      { 0x0089 ,  0x0089,
        "Platforma HD -  - Platforma HD Ltd."
      },
      { 0x0090 ,  0x0090,
        "Eutelsat 1 -  - Eutelsat"
      },
      { 0x0091 ,  0x0091,
        "Eutelsat 2 -  - Eutelsat"
      },
      { 0x0095 ,  0x0096,
        "Digiturk -  - Digiturk"
      },
      { 0x0097 ,  0x0097,
        "digiturk -  - digiturk"
      },
      { 0x0100 ,  0x011F,
        "BBC -  - BBC"
      },
      { 0x0130 ,  0x013F,
        "Eutelsat Service Guide -  - Eutelsat"
      },
      { 0x0550 ,  0x055F,
        "Eutelsat -  - Eutelsat S.A."
      },
      { 0x0560 ,  0x0560,
        "Eutelsat VisaVision Radio -  - Eutelsat S.A."
      },
      { 0x0561 ,  0x0561,
        "Eutelsat VisaVision TV -  - Eutelsat S.A."
      },
      { 0x0600 ,  0x0600,
        "Ziggo -  - Ziggo"
      },
      { 0x061F ,  0x061F,
        "BellSouth Entertainment -  - 'BellSouth Entertainment, Atlanta, GA, USA  '"
      },
      { 0x0700 ,  0x0700,
        "Almajd  -  - Almajd Satellite Broadcasting FZ LLC"
      },
      { 0x0701 ,  0x0701,
        "Almajd Plus -  - Almajd Satellite Broadcasting FZ LLC"
      },
      { 0x1000 ,  0x1000,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1000 ,  0x101F,
        "BskyB n° 1 - n° 32 -  - British Sky Broadcasting"
      },
      { 0x1020 ,  0x103F,
        "DISH Network 1 - 32 -  - Echostar Communications"
      },
      { 0x1040 ,  0x107F,
        "ARD 1 - 64 -  - ARD"
      },
      { 0x1080 ,  0x109F,
        "ZDF 1 - 32 -  - ZDF"
      },
      { 0x10A0 ,  0x10BF,
        "ORF 1 - 32 -  - ORF"
      },
      { 0x10C0 ,  0x10C0,
        "NTV+ -  - NTV +"
      },
      { 0x10C1 ,  0x10C1,
        "RTL Television -  - RTL Television "
      },
      { 0x10D1 ,  0x10D7,
        "Primacom n°1 - n°7 -  - Primacom A.G ."
      },
      { 0x10D8 ,  0x10DB,
        "Viasat n°1 - n°4 -  - Viasat  "
      },
      { 0x10DC ,  0x10DF,
        "Teracom n°1 - n°4 -  - Teracom AB  "
      },
      { 0x10E0 ,  0x10E0,
        "tividi -  - arena Sport Rechte und Marketing GmbH"
      },
      { 0x10E1 ,  0x10E1,
        "arena -  - arena Sport Rechte und Marketing GmbH"
      },
      { 0x10F0 ,  0x10F5,
        "TP S.A. -  - TP S.A."
      },
      { 0x10FA ,  0x10FA,
        "TF1 -  - TF1"
      },
      { 0x1100 ,  0x1100,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1200 ,  0x1200,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1300 ,  0x1300,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1400 ,  0x1400,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1500 ,  0x1500,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1500 ,  0x150F,
        "ExpressVu 1 - 16 -  - ExpressVu Inc."
      },
      { 0x1600 ,  0x1600,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1700 ,  0x1700,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1800 ,  0x1800,
        "FreeView NZ -  - TVNZ"
      },
      { 0x1900 ,  0x1900,
        "FreeView NZ -  - TVNZ"
      },
      { 0x2000 ,  0x2000,
        "FreeView NZ -  - TVNZ"
      },
      { 0x2000 ,  0x2000,
        "Kaleidascope Multichoice -  - Filmnet"
      },
      { 0x2001 ,  0x2001,
        "Osaka Yusen -  - StarGuide Networks "
      },
      { 0x2010 ,  0x2010,
        "WIZJATV -  - UPC Direct Programming BV "
      },
      { 0x2011 ,  0x2013,
        "WIZJATV n°1 - n°3 -  - UPC Direct Programming BV "
      },
      { 0x2020 ,  0x2022,
        "ITI Neovision S.A. -  - ITI Neovision S.A."
      },
      { 0x2100 ,  0x212F,
        "TSA 1 - 48 -  - Telefónica Servicios Audiovisuales"
      },
      { 0x2130 ,  0x2130,
        "Galaxis -  - Galaxis Technology AG  "
      },
      { 0x2140 ,  0x2140,
        "PARABOLE REUNION -  - PARABOLE REUNION"
      },
      { 0x2B00 ,  0x2B07,
        "DTT – Sky New Zealand -  - Sky Network Television Limited"
      },
      { 0x3000 ,  0x3000,
        "TPS 1 - 16 -  - La Télévision Par Satellite"
      },
      { 0x3010 ,  0x3015,
        "Sentech 1 - 6 -  - Sentech"
      },
      { 0x3100 ,  0x3100,
        "STENTOR -  - 'France Telecom, CNES and DGA'"
      },
      { 0x3200 ,  0x320F,
        "Australian Digital Television -  - Australian Terrestrial Television Networks"
      },
      { 0x322B ,  0x322B,
        "Telstra Saturn Satellite -  - TelstraSaturn Limited  "
      },
      { 0x332B ,  0x332B,
        "Telstra Saturn Cable -  - TelstraSaturn Limited  "
      },
      { 0x3622 ,  0x3622,
        "Irdeto Bouquet of Download data Services -  - Irdeto"
      },
      { 0x3623 ,  0x3623,
        "To be defined (see Wim Mooij) -  - Mindport "
      },
      { 0x3800 ,  0x3800,
        "OTE -  - OTE  "
      },
      { 0x38A0 ,  0x38A0,
        "Telstra International -  - Telstra International"
      },
      { 0x38B0 ,  0x38BF,
        "EUTELSAT -  - EUTELSAT"
      },
      { 0x3900 ,  0x3900,
        "SK-M-TV -  - Slovak Telekom, a.s."
      },
      { 0x3901 ,  0x3901,
        "SK-D-TV -  - Slovak Telecom a.s "
      },
      { 0x4000 ,  0x4000,
        "HPT -  - HPT"
      },
      { 0x4001 ,  0x4001,
        "visAvision -  - European Telecommunications Satellite Organization"
      },
      { 0x4010 ,  0x4010,
        "HRT -  - HRT"
      },
      { 0x4040 ,  0x407F,
        "OpenTV 1 - 64 -  - OpenTV Inc ."
      },
      { 0x5000 ,  0x501F,
        "BetaTechnik n° 1 - n° 32 -  - BetaTechnik"
      },
      { 0x5F00 ,  0x5FFF,
        "NDS n° 001 - n°255 -  - NDS Ltd"
      },
      { 0x6000 ,  0x6000,
        "NDS Test Bouquet -  - NDS Ltd"
      },
      { 0x6001 ,  0x6002,
        "DigiSTAR -  - STAR Television Productions Ltd"
      },
      { 0x6003 ,  0x60BF,
        "NDC 4 - 192 -  - News Datacom"
      },
      { 0x60C0 ,  0x60FF,
        "NDS n° 193 - n° 256 -  - NDS"
      },
      { 0x6100 ,  0x610F,
        "Space TV -  - TATA Group & Star"
      },
      { 0x6110 ,  0x617F,
        "NDS 6110 - 617F -  - NDS"
      },
      { 0x6180 ,  0x61FF,
        "Information Network Centre (INC) n° 1 - n° 128 -  - Information Network Centre (China)"
      },
      { 0x6200 ,  0x62FF,
        "NDS ids 6200 - 62FF -  - NDS"
      },
      { 0x6600 ,  0x6600,
        "UPC 1 -  - UPC  "
      },
      { 0x6601 ,  0x6601,
        "UPC 2 -  - UPC  "
      },
      { 0x7000 ,  0x707F,
        "MediaServices #01-#127 -  - Kabel Deutschland "
      },
      { 0x7080 ,  0x7093,
        "Unitymedia #1 - #20 -  - Unitymedia NRW GmbH"
      },
      { 0x70A0 ,  0x70A0,
        "M-net Telekommunikations GmbH -  - M-net Telekommunikations GmbH"
      },
      { 0xBBB1 ,  0xBBB9,
        "BBG #01-#09 -  - Bertelsmann Broadband Group"
      },
      { 0xBBBB ,  0xBBBB,
        "BBG -  - Bertelsmann Broadband Group  "
      },
      { 0xBBBC ,  0xBBBC,
        "SISAL -  - SISAL  "
      },
      { 0xC000 ,  0xC01F,
        "Canal+ n° 1 - n° 32 -  - Canal +"
      },
      { 0xC020 ,  0xC020,
        "VSTV -  - Canal Overseas"
      },
      { 0xC021 ,  0xC021,
        "CANAL OVERSEAS -  - CANAL OVERSEAS"
      },
      { 0xC022 ,  0xC024,
        "CYFRA+, CYFRA+ 2, CYFRA+ 3 -  - Canal+ Cyfrowy"
      },
      { 0xC030 ,  0xC031,
        "TV Numeric -  - TV Numeric"
      },
      { 0xF200 ,  0xF201,
        "Deutsche Telekom AG -  - Deutsche Telekom AG"
      },
      { 0xFC00 ,  0xFCFF,
        "France Telecom n° 1 - n° 256 -  - France Telecom Orange"
      },
      { 0xFD08 ,  0xFD08,
        "Xtra Music -  - Xtra Music "
      },