
      { 0x0000 ,  0x0000,
        "Reserved -  - "
      },
      { 0x0001 ,  0x0001,
        "IPDC SPP Open Security Framework Generic Roaming (IPDC SPP (TS 102 474) Annex A) -  - "
      },
      { 0x0002 ,  0x0002,
        "18Crypt (IPDC SPP (TS 102 474) Annex B) -  - "
      },
      { 0x0004 ,  0x0004,
        "OMA DRM Content Format – MPEG-2 TS Profile: MDCF - see OMA-TS-SCE_MDCF-V1_0 -  - "
      },
      { 0x0005 ,  0x0005,
        "OMA BCAST 1.0 (U)SIM Smartcard Profile using 3GPP GBA_U (OMA-TS-BCAST_SvcCntProtection-V1_0 section 6) -  - "
      },
      { 0x0006 ,  0x0006,
        "OMA BCAST 1.0 (U)SIM Smartcard Profile using 3GPP GBA_ME (OMA-TS-BCAST_SvcCntProtection-V1_0 section 6) -  - "
      },
      { 0x0007 ,  0x0007,
        "(Reserved for Open IPTV Forum) -  - "
      },
      { 0x0008 ,  0x0008,
        "Open Mobile Alliance -  - "
      },
      { 0x0001 ,  0x00FF,
        "Standardized systems -  - "
      },
      { 0x0100 ,  0x01FF,
        "Canal Plus -  - "
      },
      { 0x0200 ,  0x02FF,
        "CCETT -  - "
      },
      { 0x0300 ,  0x03FF,
        "Kabel Deutschland -  - "
      },
      { 0x0400 ,  0x04FF,
        "Eurodec -  - "
      },
      { 0x0500 ,  0x05FF,
        "France Telecom -  - "
      },
      { 0x0600 ,  0x06FF,
        "Irdeto -  - "
      },
      { 0x0700 ,  0x07FF,
        "Jerrold/GI/Motorola -  - "
      },
      { 0x0800 ,  0x08FF,
        "Matra Communication -  - "
      },
      { 0x0900 ,  0x09FF,
        "News Datacom -  - "
      },
      { 0x0A00 ,  0x0AFF,
        "Nokia -  - "
      },
      { 0x0B00 ,  0x0BFF,
        "Norwegian Telekom -  - "
      },
      { 0x0C00 ,  0x0CFF,
        "NTL -  - "
      },
      { 0x0D00 ,  0x0DFF,
        "CrytoWorks (Irdeto) -  - "
      },
      { 0x0E00 ,  0x0EFF,
        "Scientific Atlanta -  - "
      },
      { 0x0F00 ,  0x0FFF,
        "Sony -  - "
      },
      { 0x1000 ,  0x10FF,
        "Tandberg Television -  - "
      },
      { 0x1100 ,  0x11FF,
        "Thomson -  - "
      },
      { 0x1200 ,  0x12FF,
        "TV/Com -  - "
      },
      { 0x1300 ,  0x13FF,
        "HPT - Croatian Post and Telecommunications -  - "
      },
      { 0x1400 ,  0x14FF,
        "HRT - Croatian Radio and Television -  - "
      },
      { 0x1500 ,  0x15FF,
        "IBM -  - "
      },
      { 0x1600 ,  0x16FF,
        "Nera -  - "
      },
      { 0x1700 ,  0x17FF,
        "BetaTechnik -  - "
      },
      { 0x1800 ,  0x18FF,
        "Kudelski SA -  - "
      },
      { 0x1900 ,  0x19FF,
        "Titan Information Systems -  - "
      },
      { 0x1E00 ,  0x1E07,
        "Alticast -  - "
      },
      { 0x1EA0 ,  0x1EA0,
        "Protac -  - "
      },
      { 0x1EB0 ,  0x1EB0,
        "TELECAST TECHNOLOGY CO., LTD. -  - "
      },
      { 0x1EC0 ,  0x1EC0,
        "Cryptoguard AB -  - "
      },
      { 0x2000 ,  0x20FF,
        "Telefonica Servicios Audiovisuales -  - "
      },
      { 0x2100 ,  0x21FF,
        "STENTOR (France Telecom, CNES and DGA) -  - "
      },
      { 0x2200 ,  0x22FF,
        "Harmonic -  - "
      },
      { 0x2300 ,  0x23FF,
        "BARCO AS -  - "
      },
      { 0x2400 ,  0x24FF,
        "StarGuide Digital Networks -  - "
      },
      { 0x2500 ,  0x25FF,
        "Mentor Data System, Inc. -  - "
      },
      { 0x2600 ,  0x26FF,
        "European Broadcasting Union -  - "
      },
      { 0x2700 ,  0x270F,
        "PolyCipher (NGNA, LLC) -  - "
      },
      { 0x2710 ,  0x2711,
        "Extended Secure Technologies B.V. -  - "
      },
      { 0x2712 ,  0x2712,
        "Derincrypt -  - "
      },
      { 0x2713 ,  0x2714,
        "Wuhan Tianyu Information Industry Co., Ltd  -  - "
      },
      { 0x2715 ,  0x2715,
        "Network Broadcast -  - "
      },
      { 0x2716 ,  0x2716,
        "Bromteck -  - "
      },
      { 0x2717 ,  0x2718,
        "LOGIWAYS -  - "
      },
      { 0x2719 ,  0x2719,
        "S-Curious Research and Technology Private Limited -  - "
      },
      { 0x2800 ,  0x2809,
        "LCS LLC -  - "
      },
      { 0x2810 ,  0x2810,
        "MULTIKOM DELTASAT GMBH KG -  - "
      },
      { 0x4347 ,  0x4347,
        "Crypton -  - "
      },
      { 0x4700 ,  0x47FF,
        "General Instrument (Motorola) -  - "
      },
      { 0x4825 ,  0x4825,
        "ChinaEPG (Beijing) Technology Co., Ltd. -  - "
      },
      { 0x4800 ,  0x48FF,
        "Telemann -  - "
      },
      { 0x4900 ,  0x49FF,
        "CrytoWorks (China) (Irdeto) -  - "
      },
      { 0x4A10 ,  0x4A1F,
        "Easycas -  - "
      },
      { 0x4A20 ,  0x4A2F,
        "AlphaCrypt -  - "
      },
      { 0x4A30 ,  0x4A3F,
        "DVN Holdings -  - "
      },
      { 0x4A40 ,  0x4A4F,
        "Shanghai Advanced Digital Technology Co. Ltd. (ADT) -  - "
      },
      { 0x4A50 ,  0x4A5F,
        "Shenzhen Kingsky Company (China) Ltd. -  - "
      },
      { 0x4A60 ,  0x4A6F,
        "NEOTION SA -  - "
      },
      { 0x4A70 ,  0x4A7F,
        "Dreamcrypt -  - "
      },
      { 0x4A80 ,  0x4A8F,
        "THALESCrypt -  - "
      },
      { 0x4A90 ,  0x4A9F,
        "Runcom Technologies -  - "
      },
      { 0x4AA0 ,  0x4AAF,
        "SIDSA -  - "
      },
      { 0x4AB0 ,  0x4ABF,
        "Beijing Compunicate Technology Inc. -  - "
      },
      { 0x4AC0 ,  0x4ACF,
        "Latens Systems Ltd -  - "
      },
      { 0x4AD0 ,  0x4AD1,
        "XCrypt Inc. -  - "
      },
      { 0x4AD2 ,  0x4AD3,
        "Beijing Digital Video Technology Co., Ltd. -  - "
      },
      { 0x4AD4 ,  0x4AD5,
        "Widevine Technologies, Inc. -  - "
      },
      { 0x4AD6  ,  0x4AD7,
        "SK Telecom Co., Ltd. -  - "
      },
      { 0x4AD8  ,  0x4AD9,
        "Enigma Systems -  - "
      },
      { 0x4ADA ,  0x4ADA,
        "Wyplay SAS -  - "
      },
      { 0x4ADB ,  0x4ADB,
        "Jinan Taixin Electronics, Co., Ltd. -  - "
      },
      { 0x4ADC ,  0x4ADC,
        "LogiWays -  - "
      },
      { 0x4ADD ,  0x4ADD,
        "ATSC System Renewability Message (SRM) -  - "
      },
      { 0x4ADE ,  0x4ADE,
        "CerberCrypt -  - "
      },
      { 0x4ADF ,  0x4ADF,
        "Caston Co., Ltd. -  - "
      },
      { 0x4AE0 ,  0x4AE1,
        "Cifra LLC -  - "
      },
      { 0x4AE2 ,  0x4AE3,
        "Microsoft Corp. -  - "
      },
      { 0x4AE4 ,  0x4AE4,
        "Coretrust, Inc. -  - "
      },
      { 0x4AE5 ,  0x4AE5,
        "IK SATPROF -  - "
      },
      { 0x4AE6 ,  0x4AE6,
        "SypherMedia International -  - "
      },
      { 0x4AE7 ,  0x4AE7,
        "Guangzhou Ewider Technology Corporation Limited  -  - "
      },
      { 0x4AE8 ,  0x4AE8,
        "FG DIGITAL Ltd. -  - "
      },
      { 0x4AE9 ,  0x4AE9,
        "Dreamer-i Co., Ltd. -  - "
      },
      { 0x4AEA ,  0x4AEA,
        "Cryptoguard AB -  - "
      },
      { 0x4AEB ,  0x4AEB,
        "Abel DRM Systems AS -  - "
      },
      { 0x4AEC ,  0x4AEC,
        "FTS DVL SRL -  - "
      },
      { 0x4AED ,  0x4AED,
        "Unitend Technologies, Inc. -  - "
      },
      { 0x4AEE ,  0x4AEE,
        "Deltacom Electronics OOD -  - "
      },
      { 0x4AEF ,  0x4AEF,
        "NetUP Inc. -  - "
      },
      { 0x4AF0 ,  0x4AF0,
        "Beijing Alliance Broadcast Vision Technology Co., Ltd. -  - "
      },
      { 0x4AF1 ,  0x4AF1,
        "China DTV Media Inc., Ltd. #1 -  - "
      },
      { 0x4AF2 ,  0x4AF2,
        "China DTV Media Inc., Ltd. #2 -  - "
      },
      { 0x4AF3 ,  0x4AF3,
        "Baustem Information Technologies, Ltd. -  - "
      },
      { 0x4AF4 ,  0x4AF4,
        "Marlin Developer Community, LLC -  - "
      },
      { 0x4AF5 ,  0x4AF5,
        "SecureMedia -  - "
      },
      { 0x4AF6 ,  0x4AF6,
        "Tongfang CAS -  - "
      },
      { 0x4AF7 ,  0x4AF7,
        "MSA -  - "
      },
      { 0x4AF8 ,  0x4AF8,
        "Griffin CAS -  - "
      },
      { 0x4AF9 ,  0x4AFA,
        "Beijing Topreal Technologies Co., Ltd -  - "
      },
      { 0x4AFB ,  0x4AFB,
        "NST -  - "
      },
      { 0x4AFC ,  0x4AFC,
        "Panaccess Systems GmbH -  - "
      },
      { 0x4AFD ,  0x4AFD,
        "Comteza SIA -  - "
      },
      { 0x4B00 ,  0x4B02,
        "Tongfang CAS -  - "
      },
      { 0x4B03 ,  0x4B03,
        "DuoCrypt -  - "
      },
      { 0x4B04 ,  0x4B04,
        "Great Wall CAS -  - "
      },
      { 0x4B05 ,  0x4B06,
        "DIGICAP -  - "
      },
      { 0x4B07 ,  0x4B07,
        "Wuhan Reikost Technology Co., Ltd. -  - "
      },
      { 0x4B08 ,  0x4B08,
        "Philips -  - "
      },
      { 0x4B09 ,  0x4B09,
        "Ambernetas -  - "
      },
      { 0x4B0A ,  0x4B0B,
        "Beijing Sumavision Technologies CO. LTD. -  - "
      },
      { 0x4B0C ,  0x4B0F,
        "Sichuan changhong electric co.,ltd. -  - "
      },
      { 0x4B10 ,  0x4B10,
        "Exterity Limited -  - "
      },
      { 0x4B11 ,  0x4B12,
        "Advanced Digital Platform Technologies -  - "
      },
      { 0x4B13 ,  0x4B14,
        "Microsoft Corporation -  - "
      },
      { 0x4B20 ,  0x4B22,
        "MULTIKOM DELTASAT GmbH Co KG -  - "
      },
      { 0x4B23 ,  0x4B23,
        "SkyNLand Video Networks Pvt Ltd -  - "
      },
      { 0x5347 ,  0x5347,
        "GkWare e.K. -  - "
      },
      { 0x5601 ,  0x5601,
        "Verimatrix, Inc. #1 -  - "
      },
      { 0x5602 ,  0x5602,
        "Verimatrix, Inc. #2 -  - "
      },
      { 0x5603 ,  0x5603,
        "Verimatrix, Inc. #3 -  - "
      },
      { 0x5604 ,  0x5604,
        "Verimatrix, Inc. #4 -  - "
      },
      { 0x5605 ,  0x5606,
        "Sichuan Juizhou Electronic Co. Ltd -  - "
      },
      { 0x5607 ,  0x5608,
        "Viewscenes -  - "
      },
      { 0x5609 ,  0x5609,
        "Power On  s.r.l -  - "
      },
      { 0x7BE0 ,  0x7BE1,
        "OOO  -  - "
      },
      { 0xAA00 ,  0xAA00,
        "Best CAS Ltd -  - "
      },
      { 0xAA01 ,  0xAA01,
        "BestCAS Ltd -  - "
      },