
      { 0x0000 ,  0x0000,
        "Reserved for future use -  - Reserved for future use"
      },
      { 0x0001 ,  0x0001,
        "Data pipe -  - Data pipe"
      },
      { 0x0002 ,  0x0002,
        "Asynchronous data stream -  - Asynchronous data stream"
      },
      { 0x0003 ,  0x0003,
        "Synchronous data stream -  - Synchronous data stream"
      },
      { 0x0004 ,  0x0004,
        "Synchronised data stream -  - Synchronised data stream"
      },
      { 0x0005 ,  0x0005,
        "Multi protocol encapsulation -  - Multi protocol encapsulation"
      },
      { 0x0006 ,  0x0006,
        "Data Carousel -  - Data Carousel"
      },
      { 0x0007 ,  0x0007,
        "Object Carousel -  - Object Carousel"
      },
      { 0x0008 ,  0x0008,
        "DVB ATM streams -  - DVB ATM streams"
      },
      { 0x0009 ,  0x0009,
        "Higher Protocols based on asynchronous data streams -  - Higher Protocols based on asynchronous data streams"
      },
      { 0x000A ,  0x000A,
        "System Software Update service [TS 102 006] -  - System Software Update service [TS 102 006]"
      },
      { 0x000B ,  0x000B,
        "IP/MAC Notification service [EN 301 192] -  - IP/MAC Notification service [EN 301 192]"
      },
      { 0x000C ,  0x00EF,
        "Reserved for future use by DVB -  - Reserved for future use by DVB"
      },
      { 0x00F0 ,  0x00F0,
        "MHP Object Carousel -  - MHP Object Carousel"
      },
      { 0x00F1 ,  0x00F1,
        "reserved for MHP Multi Protocol Encapsulation -  - reserved for MHP Multi Protocol Encapsulation"
      },
      { 0x00F2 ,  0x00FE,
        "Reserved for MHP use -  - Reserved for MHP use"
      },
      { 0x00FF ,  0x00FF,
        "Reserved for future use by DVB -  - Reserved for future use by DVB"
      },
      { 0x0100 ,  0x0100,
        "Eutelsat Data Piping -  - Eutelsat Data Piping"
      },
      { 0x0101 ,  0x0101,
        "Eutelsat Data Streaming -  - Eutelsat Data Streaming"
      },
      { 0x0102 ,  0x0102,
        "SAGEM IP encapsulation in MPEG-2 PES packets -  - SAGEM IP encapsulation in MPEG-2 PES packets"
      },
      { 0x0103 ,  0x0103,
        "BARCO Data Broadcasting -  - BARCO Data Broadcasting"
      },
      { 0x0104 ,  0x0104,
        "CyberCity Multiprotocol Encapsulation (New Media Communications Ltd.) -  - CyberCity Multiprotocol Encapsulation (New Media Communications Ltd.)"
      },
      { 0x0105 ,  0x0105,
        "CyberSat Multiprotocol Encapsulation (New Media Communications Ltd.) -  - CyberSat Multiprotocol Encapsulation (New Media Communications Ltd.)"
      },
      { 0x0106 ,  0x0106,
        "The Digital Network  -  - The Digital Network "
      },
      { 0x0107 ,  0x0107,
        "OpenTV Data Carousel  -  - OpenTV Data Carousel "
      },
      { 0x0108 ,  0x0108,
        "Panasonic   -  - Panasonic  "
      },
      { 0x0109 ,  0x0109,
        "Kabel Deutschland   -  - Kabel Deutschland  "
      },
      { 0x010A ,  0x010A,
        "TechnoTrend Görler GmbH -  - TechnoTrend Görler GmbH"
      },
      { 0x010B ,  0x010B,
        "NDS France Technologies system software download -  - NDS France Technologies system software download"
      },
      { 0x010C ,  0x010C,
        "GUIDE Plus+ -  - Rovi Corporation"
      },
      { 0x010D ,  0x010D,
        "ACAP Object Carousel -  - ACAP Object Carousel"
      },
      { 0x010E ,  0x010E,
        "Micronas Download Stream -  - Micronas Download Stream"
      },
      { 0x0110 ,  0x0110,
        "Televizja Polsat   -  - Televizja Polsat  "
      },
      { 0x0111 ,  0x0111,
        "UK DTG   -  - UK DTG  "
      },
      { 0x0112 ,  0x0112,
        "SkyMedia   -  - SkyMedia  "
      },
      { 0x0113 ,  0x0113,
        "Intellibyte DataBroadcasting -  - Intellibyte DataBroadcasting"
      },
      { 0x0114 ,  0x0114,
        "TeleWeb Data Carousel -  - TeleWeb Data Carousel"
      },
      { 0x0115 ,  0x0115,
        "TeleWeb Object Carousel -  - TeleWeb Object Carousel"
      },
      { 0x0116 ,  0x0116,
        "TeleWeb -  - TeleWeb"
      },
      { 0x0117 ,  0x0117,
        "BBC -  - BBC"
      },
      { 0x0118 ,  0x0118,
        "Electra Entertainment Ltd -  - Electra Entertainment Ltd"
      },
      { 0x0119 ,  0x011A,
        "BBC 2 - 3 -  - BBC 2 - 3"
      },
      { 0x011B ,  0x011B,
        "Teletext -  - Teletext"
      },
      { 0x011C ,  0x0120,
        "Sky Download Streams 1-5 -  - Sky Download Streams 1-5"
      },
      { 0x0121 ,  0x0121,
        "ICO mim -  - ICO mim"
      },
      { 0x0122 ,  0x0122,
        "CI+ Data Carousel -  - CI+ Data Carousel"
      },
      { 0x0123 ,  0x0123,
        "HBBTV Carousel -  - HBBTV Carousel"
      },
      { 0x0124 ,  0x0124,
        "Premium Content from Rovi -  - Rovi Corporation"
      },
      { 0x0125 ,  0x0125,
        "Media Guide from Rovi -  - Rovi Corporation"
      },
      { 0x0126 ,  0x0126,
        "InView Technology Ltd -  - InView Technology Ltd"
      },
      { 0x0130 ,  0x0130,
        "BOTECH ELEKTRONIK SAN. ve TIC. LTD.STI. -  - BOTECH ELEKTRONIK SAN. ve TIC. LTD.STI."
      },
      { 0x0131 ,  0x0131,
        "Scilla Push-VOD Carousel -  - Scilla Systems Ltd."
      },
      { 0x0140 ,  0x0140,
        "CANAL+ -  - CANAL+"
      },
      { 0x0150 ,  0x0150,
        "OIPF Object Carousel -  - Open IPTV Forum"
      },
      { 0x0160 ,  0x0160,
        "Samsung Electronics (UK) Limited -  - Samsung Electronics (UK) Limited"
      },
      { 0x0170 ,  0x0170,
        "Digital TV Group -  - Digital TV Group"
      },
      { 0x0180 ,  0x0181,
        "South African Broadcasting Corporation -  - South African Broadcasting Corporation"
      },
      { 0x4444 ,  0x4444,
        "4TV Data Broadcast -  - 4TV Data Broadcast"
      },
      { 0x4E4F ,  0x4E4F,
        "Nokia IP based software delivery -  - Nokia IP based software delivery"
      },
      { 0xBBB1 ,  0xBBB1,
        "BBG Data Caroussel   -  - BBG Data Caroussel  "
      },
      { 0xBBB2 ,  0xBBB2,
        "BBG Object Caroussel   -  - BBG Object Caroussel  "
      },
      { 0xBBBB ,  0xBBBB,
        "Bertelsmann Broadband Group   -  - Bertelsmann Broadband Group  "
      },
      { 0xFFFF ,  0xFFFF,
        "Reserved for future use -  - Reserved for future use"
      },