
      { 0x0000 ,  0x0000,
        "Reserved - Reserved - Reserved"
      },
      { 0x0001 ,  0x0001,
        "Astra Satellite Network 19,2°E - Satellite - Société Européenne des Satellites"
      },
      { 0x0002 ,  0x0002,
        "Astra Satellite Network 28,2°E - Satellite - Société Européenne des Satellites"
      },
      { 0x0003 ,  0x0019,
        "Astra 1 - 23 - Satellite - Société Européenne des Satellites"
      },
      { 0x001A ,  0x001A,
        "Intelsat IS-907 at 332.5E - Satellite - Intelsat"
      },
      { 0x001B ,  0x001B,
        "TrendTV - Satellite - Communication Trends Ltd."
      },
      { 0x001C ,  0x001C,
        "HELLAS SAT - Satellite - Hellas-Sat S.A."
      },
      { 0x001D ,  0x001D,
        "NRK - IPTV - NRK"
      },
      { 0x0020 ,  0x0020,
        "ASTRA - Satellite - Société Européenne des Satellites"
      },
      { 0x0021 ,  0x0026,
        "Hispasat Network 1 - 6 - Satellite - Hispasat S.A ."
      },
      { 0x0027 ,  0x0029,
        "Hispasat 30°W - Satellite - Hispasat FSS"
      },
      { 0x002A ,  0x002A,
        "Multicanal - Satellite - Multicanal  "
      },
      { 0x002B ,  0x002B,
        "Telstra Saturn Satellite - Satellite - TelstraSaturn Limited  "
      },
      { 0x002C ,  0x002C,
        "Orbit Satellite Television and Radio Network - Satellite - Orbit Communications Company  "
      },
      { 0x002D ,  0x002D,
        "Alpha TV - Satellite - Alpha Digital Synthesis S.A."
      },
      { 0x002E ,  0x002E,
        "Xantic - Satellite - Xantic BU Broadband"
      },
      { 0x002F ,  0x002F,
        "TVNZ Digital - Satellite - TVNZ  "
      },
      { 0x0030 ,  0x0030,
        "Canal+ Satellite Network - Satellite - Canal+ SA (for Intelsat 601)"
      },
      { 0x0031 ,  0x0031,
        "Hispasat – VIA DIGITAL - Satellite - Hispasat S.A."
      },
      { 0x0032 ,  0x0034,
        "Hispasat Network 7 - 9 - Satellite - Hispasat S.A."
      },
      { 0x0035 ,  0x0035,
        "TV Africa - Satellite - Telemedia (PTY) Ltd"
      },
      { 0x0036 ,  0x0036,
        "TV Cabo - Satellite - TV Cabo Portugal  "
      },
      { 0x0037 ,  0x0037,
        "STENTOR - Satellite - France Telecom, CNES and DGA"
      },
      { 0x0038 ,  0x0038,
        "OTE - Satellite - Hellenic Telecommunications Organization S.A ."
      },
      { 0x0039 ,  0x0039,
        "PMSI - Satellite - PMSI (Philippines )"
      },
      { 0x003A ,  0x003A,
        "Bharat Business Channel - Satellite - Bharat Business Channel Limited"
      },
      { 0x003B ,  0x003B,
        "BBC - Satellite - BBC"
      },
      { 0x003C ,  0x003C,
        "ICO mim - Satellite - ICO Satellite Services G.P."
      },
      { 0x003D ,  0x003D,
        "Eutelsat satellite system at 3°East - Satellite - Skylogic Italia S.A."
      },
      { 0x003E ,  0x003F,
        "Eutelsat satellite system at 3°East - Satellite - Eutelsat S.A."
      },
      { 0x0040 ,  0x0040,
        "Hrvatski Telekom d.d - To be defined - Hrvatski Telekom d.d"
      },
      { 0x0041 ,  0x0041,
        "To be defined See Wim Mooij - Satellite - Mindport  "
      },
      { 0x0042 ,  0x0042,
        "DMG - Satellite - DTV haber ve Gorsel yayýncilik"
      },
      { 0x0044 ,  0x0044,
        "VisionTV - Satellite - VisionTV LLC"
      },
      { 0x0045 ,  0x0045,
        "Vision TV - Satellite - SES-Sirius"
      },
      { 0x0046 ,  0x0047,
        "1 degree W - Satellite - Telenor"
      },
      { 0x0048 ,  0x0048,
        "STAR DIGITAL - Satellite - STAR DIGITAL A.S ."
      },
      { 0x0049 ,  0x0049,
        "Sentech Digital Satellite - Satellite - Sentech  "
      },
      { 0x004A ,  0x004B,
        "Eutelsat satellite system at 4°East - Satellite - Rambouillet ES"
      },
      { 0x004C ,  0x004C,
        "Eutelsat satellite system at 4°East - Satellite - Skylogic S.A."
      },
      { 0x004D ,  0x004D,
        "Eutelsat satellite system at 4°East - Satellite - Skylogic S.A."
      },
      { 0x004E ,  0x004F,
        "Eutelsat satellite system at 4°East - Satellite - Eutelsat S.A."
      },
      { 0x0050 ,  0x0050,
        "HRT – Croatian Radio and Television - To be defined - HRT – Croatian Radio and Television"
      },
      { 0x0051 ,  0x0051,
        "Havas - Satellite - Havas "
      },
      { 0x0052 ,  0x0052,
        "PT Comunicações - Satellite - PT Comunicações"
      },
      { 0x0053 ,  0x0053,
        "PT Comunicações - Satellite - PT Comunicações"
      },
      { 0x0054 ,  0x0054,
        "Teracom Satellite - Satellite - Teracom AB Satellite Services"
      },
      { 0x0055 ,  0x0055,
        "Sirius Satellite System European Coverage - Satellite - NSAB (Teracom)"
      },
      { 0x0056 ,  0x0056,
        "Viasat Satellite Services AB - Satellite - Viasat Satellite Services AB"
      },
      { 0x0058 ,  0x0058,
        "Thiacom 1 & 2 co-located 78.5°E - Satellite - UBC Thailand "
      },
      { 0x005C ,  0x005C,
        "TNL PCS - Satellite - TNL PCS"
      },
      { 0x005E ,  0x005E,
        "Sirius Satellite System Nordic Coverage - Satellite - NSAB "
      },
      { 0x005F ,  0x005F,
        "Sirius Satellite System FSS - Satellite - NSAB "
      },
      { 0x0060 ,  0x0060,
        "Kabel Deutschland - Satellite - Kabel Deutschland"
      },
      { 0x0064 ,  0x0064,
        "T-Kábel - Satellite - T-Kábel Magyarország Kft."
      },
      { 0x0069 ,  0x0069,
        "Optus B3 156°E - Satellite - Optus Communications"
      },
      { 0x0070 ,  0x0070,
        "BONUM1; 36 Degrees East - Satellite - NTV+"
      },
      { 0x0071 ,  0x0071,
        "TV Polsat - Satellite - Telewizja Polsat  "
      },
      { 0x0073 ,  0x0073,
        "PanAmSat 4 68.5°E - Satellite - Pan American Satellite System"
      },
      { 0x0074 ,  0x0074,
        "GeoTel LMI - Satellite - GeoTelecom Satellite Services"
      },
      { 0x0075 ,  0x0075,
        "GeoTel Express - Satellite - GeoTelecom Satellite Services"
      },
      { 0x0076 ,  0x0076,
        "GeoTel 3 - Satellite - GeoTelecom Satellite Services"
      },
      { 0x007D ,  0x007D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x007E ,  0x007F,
        "Eutelsat Satellite System at 7°E - Satellite - European Telecommunications Satellite Organization"
      },
      { 0x0085 ,  0x0085,
        "Sky Deutschland GmbH & Co. KG - Satellite - Sky Deutschland GmbH & Co. KG"
      },
      { 0x0090 ,  0x0090,
        "National network - Terrestrial - TDF"
      },
      { 0x009A ,  0x009B,
        "Eutelsat satellite system at 9°East - Satellite - Rambouillet ES"
      },
      { 0x009C ,  0x009D,
        "Eutelsat satellite system at 9°East - Satellite - Skylogic S.A."
      },
      { 0x009E ,  0x009F,
        "Eutelsat satellite system at 9°East - Satellite - Eutelsat S.A."
      },
      { 0x00A0 ,  0x00A0,
        "CyberStar - Satellite - Loral Space and Communications  Ltd. (NDS)"
      },
      { 0x00A1 ,  0x00A1,
        "DigiSTAR - Satellite - STAR Television Productions Ltd (HK) (NDS)"
      },
      { 0x00A2 ,  0x00A2,
        "Sky Entertainment Services - Satellite - NetSat Serviços Ltda (Brazil), Innova S. de R. L. (Mexico) and Multicountry Partnership L. P. (NDS)"
      },
      { 0x00A3 ,  0x00A3,
        "NDS Director Systems - Satellite - Various (NDS)"
      },
      { 0x00A4 ,  0x00A4,
        "ISkyB - Satellite - STAR Television Productions Ltd (HK) (NDS)"
      },
      { 0x00A5 ,  0x00A5,
        "Indovision - Satellite - PT. Matahari Lintas Cakrawala (MLC) (NDS)"
      },
      { 0x00A6 ,  0x00A6,
        "ART - Satellite - ART"
      },
      { 0x00A7 ,  0x00A7,
        "Globecast - Satellite - France Telecom (NDS)"
      },
      { 0x00A8 ,  0x00A8,
        "Foxtel - Satellite - Foxtel (Australia) (NDS)"
      },
      { 0x00A9 ,  0x00A9,
        "Sky New Zealand - Satellite - Sky Network Television Ltd (NDS)"
      },
      { 0x00AA ,  0x00AA,
        "OTE - Satellite - OTE (Greece) (NDS)"
      },
      { 0x00AB ,  0x00AB,
        "Yes Satellite Services - Satellite - DBS (Israel) (NDS)"
      },
      { 0x00AC ,  0x00AC,
        "(NDS satellite services) - Satellite - (NDS to be allocated)"
      },
      { 0x00AD ,  0x00AD,
        "SkyLife - Satellite - Korea Digital Broadcasting (NDS)"
      },
      { 0x00AE ,  0x00AF,
        "(NDS satellite services) - Satellite - (NDS to be allocated)"
      },
      { 0x00B0 ,  0x00B0,
        "Groupe CANAL+ - Satellite - Groupe CANAL+"
      },
      { 0x00B1 ,  0x00B3,
        "CANAL+ OVERSEAS - Satellite - CANAL+ OVERSEAS"
      },
      { 0x00B4 ,  0x00B4,
        "Telesat 107.3°W - Satellite - Telesat Canada"
      },
      { 0x00B5 ,  0x00B5,
        "Telesat 111.1°W - Satellite - Telesat Canada"
      },
      { 0x00B7 ,  0x00B7,
        "REAL Digital EPG Services Limited - Satellite - REAL Digital EPG Services Limited"
      },
      { 0x00B8 ,  0X00B8,
        "W1 - Neterra White Label DTH - Satellite, Cable - Neterra Communications Ltd."
      },
      { 0x00BB ,  0x00BB,
        "Slovak Telekom, a.s. - Satellite - Slovak Telekom, a.s."
      },
      { 0x00C0 ,  0x00CD,
        "Canal + - Satellite, Cable - Canal+"
      },
      { 0x00D0 ,  0x00D0,
        "CCTV - Satellite, Cable - China Central Television (NDS)"
      },
      { 0x00D1 ,  0x00D1,
        "Galaxy - Satellite - Galaxy Satellite Broadcasting (HK) (NDS)"
      },
      { 0x00D0 ,  0x00DF,
        "Päijät-Hämeen Puhelin Oyj - Satellite - Päijät-Hämeen Puhelin Oyj"
      },
      { 0x00D2 ,  0x00DF,
        "(NDS satellite services) - Satellite - (NDS to be allocated)"
      },
      { 0x00E0 ,  0x00E0,
        "Es’hailSat - Satellite - Es’hailSat"
      },
      { 0x00EB ,  0x00EB,
        "Eurovision Network - Satellite - European Broadcasting Union  "
      },
      { 0x0100 ,  0x0103,
        "ExpressVu 1 - 4 - Satellite - ExpressVu Inc."
      },
      { 0x0104 ,  0x0104,
        "MagtiSat - Satellite - Magticom Ltd."
      },
      { 0x010D ,  0x010D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x010E ,  0x010F,
        "Eutelsat Satellite System at 10°E - Satellite - European Telecommunications Satellite Organization"
      },
      { 0x0110 ,  0x0110,
        "Mediaset - Satellite - Mediaset "
      },
      { 0x011F ,  0x011F,
        "visAvision Satellite Network - Satellite - European Telecommunications Satellite Organization"
      },
      { 0x013D ,  0x013D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x013E ,  0x013F,
        "Eutelsat Satellite System at 13°E - Satellite - European Telecommunications Satellite Organization"
      },
      { 0x016D ,  0x016D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x016E ,  0x016F,
        "Eutelsat Satellite System at 16°E - Satellite - European Telecommunications Satellite Organization"
      },
      { 0x0170 ,  0x0171,
        "Audio Visual Global Joint Stock Company - Satellite - Audio Visual Global Joint Stock Company"
      },
      { 0x022D ,  0x022D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x022E ,  0x022F,
        "Eutelsat Satellite System at 21.5°E - Satellite - EUTELSAT – European Telecommunications Satellite Organization "
      },
      { 0x026D ,  0x026D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x026E ,  0x026F,
        "Eutelsat Satellite System at 25.5°E - Satellite - EUTELSAT – European Telecommunications Satellite Organization "
      },
      { 0x029D ,  0x029D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x029E ,  0x029F,
        "Eutelsat Satellite System at 29°E - Satellite - European Telecommunications Satellite Organization"
      },
      { 0x02BE ,  0x02BE,
        "ARABSAT - Satellite - ARABSAT - Arab Satellite Communications Organization"
      },
      { 0x02C0 ,  0x02C0,
        "MTV Networks Europe - Satellite - MTV Networks Europe"
      },
      { 0x033D ,  0x033D,
        "Skylogic at 33°E - Satellite - Skylogic Italia"
      },
      { 0x033E ,  0x033F,
        "Eutelsat Satellite System at 33°E - Satellite - Eutelsat"
      },
      { 0x034E ,  0x034E,
        "IRIB - Satellite - IRIB"
      },
      { 0x036D ,  0x036D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x036E ,  0x036F,
        "Eutelsat Satellite System at 36°E - Satellite - European Telecommunications Satellite Organization"
      },
      { 0x0378 ,  0x0378,
        "Selectv - Satellite - Selectv"
      },
      { 0x03E8 ,  0x03E8,
        "Telia - Satellite - Telia, Sweden"
      },
      { 0x045D ,  0x045F,
        "Eutelsat satellite system at 15°West - Satellite - Eutelsat S.A."
      },
      { 0x047D ,  0x047D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x047E ,  0x047F,
        "Eutelsat Satellite System at 12.5°W - Satellite - EUTELSAT – European Telecommunications Satellite Organization "
      },
      { 0x048D ,  0x048D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x048E ,  0x048F,
        "Eutelsat Satellite System at 48°E - Satellite - European Telecommunications Satellite Organization"
      },
      { 0x049D ,  0x049F,
        "Eutelsat satellite system at 11°West - Satellite - Eutelsat S.A."
      },
      { 0x0500 ,  0x0500,
        "Vinasat Center - Satellite - Vinasat Center"
      },
      { 0x052D ,  0x052D,
        "Skylogic - Satellite - Skylogic Italia"
      },
      { 0x052E ,  0x052F,
        "Eutelsat Satellite System at 8°W - Satellite - EUTELSAT – European Telecommunications Satellite Organization "
      },
      { 0x0530 ,  0x0530,
        "PT Comunicações - Satellite - PT Comunicações"
      },
      { 0x053D ,  0x053F,
        "Eutelsat satellite system at 53°East - Satellite - Eutelsat S.A."
      },
      { 0x055D ,  0x055D,
        "Skylogic at 5°W - Satellite - Skylogic Italia"
      },
      { 0x055E ,  0x055F,
        "Eutelsat Satellite System at 5°W - Satellite - Eutelsat"
      },
      { 0x0601 ,  0x0601,
        "UPC Satellite - Satellite - UPC  "
      },
      { 0x0616 ,  0x0616,
        "BellSouth Entertainment - Satellite - BellSouth Entertainment, Atlanta, GA, USA  "
      },
      { 0x071D ,  0x071D,
        "Skylogic Satellite System at 70.5°E - Satellite - Skylogic Italia"
      },
      { 0x071E ,  0x071F,
        "Eutelsat Satellite System at 70.5°E - Satellite - Eutelsat S.A."
      },
      { 0x077D ,  0x077D,
        "Skylogic Satellite System at 7°W - Satellite - Skylogic Italia"
      },
      { 0x077E ,  0x077F,
        "Eutelsat Satellite System at 7°W - Satellite - Eutelsat S.A."
      },
      { 0x0800 ,  0x0800,
        "Nilesat 101 - Satellite - Nilesat"
      },
      { 0x0880 ,  0x0880,
        "MEASAT 1, 91.5°E - Satellite - MEASAT Broadcast Network Systems SDN. BHD. (Kuala Lumpur, Malaysia)"
      },
      { 0x0882 ,  0x0882,
        "MEASAT 2, 91.5°E - Satellite - MEASAT Broadcast Network Systems SDN. BHD. (Kuala Lumpur, Malaysia)"
      },
      { 0x0883 ,  0x0883,
        "MEASAT 2, 148.0°E - Satellite - Hsin Chi Broadcast Company Ltd ."
      },
      { 0x088F ,  0x088F,
        "MEASAT 3 - Satellite - MEASAT Broadcast Network Systems SDN. BHD. (Kuala Lumpur, Malaysia)"
      },
      { 0x0E26 ,  0x0E26,
        "IRIB - Satellite - IRIB"
      },
      { 0x0E30 ,  0x0E30,
        "Telstra International - Satellite - Telstra International"
      },
      { 0x1000 ,  0x1000,
        "Optus B3 156°E - Satellite - Optus Communications"
      },
      { 0x1001 ,  0x1001,
        "DISH Network - Satellite - Echostar Communications"
      },
      { 0x1002 ,  0x1002,
        "Dish Network 61.5 W - Satellite - Echostar Communications"
      },
      { 0x1003 ,  0x1003,
        "Dish Network 83 W - Satellite - Echostar Communications"
      },
      { 0x1004 ,  0x1004,
        "Dish Network 119 W - Satellite - Echostar Communications"
      },
      { 0x1005 ,  0x1005,
        "Dish Network 121 W - Satellite - Echostar Communications"
      },
      { 0x1006 ,  0x1006,
        "Dish Network 148 W - Satellite - Echostar Communications"
      },
      { 0x1007 ,  0x1007,
        "Dish Network 175 W - Satellite - Echostar Communications"
      },
      { 0x1008 ,  0x100B,
        "Dish Network W - Z - Satellite - Echostar Communications"
      },
      { 0x1100 ,  0x110F,
        "GE Americom - Satellite - GE American Communications"
      },
      { 0x1111 ,  0x1111,
        "EASTERN SPACE SYSTEMS - Satellite - EASTERN SPACE SYSTEMS"
      },
      { 0x1700 ,  0x1700,
        "Echostar 2A - Satellite - EchoStar Communications"
      },
      { 0x1701 ,  0x1701,
        "Echostar 2B - Satellite - EchoStar Communications"
      },
      { 0x1702 ,  0x1702,
        "Echostar 2C - Satellite - EchoStar Communications"
      },
      { 0x1703 ,  0x1703,
        "Echostar 2D - Satellite - EchoStar Communications"
      },
      { 0x1704 ,  0x1704,
        "Echostar 2E - Satellite - EchoStar Communications"
      },
      { 0x1705 ,  0x1705,
        "Echostar 2F - Satellite - EchoStar Communications"
      },
      { 0x1706 ,  0x1706,
        "Echostar 2G - Satellite - EchoStar Communications"
      },
      { 0x1707 ,  0x1707,
        "Echostar 2H - Satellite - EchoStar Communications"
      },
      { 0x1708 ,  0x1708,
        "Echostar 2I - Satellite - EchoStar Communications"
      },
      { 0x1709 ,  0x1709,
        "Echostar 2J - Satellite - EchoStar Communications"
      },
      { 0x170A ,  0x170A,
        "Echostar 2K - Satellite - EchoStar Communications"
      },
      { 0x170B ,  0x170B,
        "Echostar 2L - Satellite - EchoStar Communications"
      },
      { 0x170C ,  0x170C,
        "Echostar 2M - Satellite - EchoStar Communications"
      },
      { 0x170D ,  0x170D,
        "Echostar 2N - Satellite - EchoStar Communications"
      },
      { 0x170E ,  0x170E,
        "Echostar 2O - Satellite - EchoStar Communications"
      },
      { 0x170F ,  0x170F,
        "Echostar 2P - Satellite - EchoStar Communications"
      },
      { 0x1710 ,  0x1710,
        "Echostar 2Q - Satellite - EchoStar Communications"
      },
      { 0x1711 ,  0x1711,
        "Echostar 2R - Satellite - EchoStar Communications"
      },
      { 0x1712 ,  0x1712,
        "Echostar 2S - Satellite - EchoStar Communications"
      },
      { 0x1713 ,  0x1713,
        "Echostar 2T - Satellite - EchoStar Communications"
      },
      { 0x1714 ,  0x1714,
        "Platforma HD - Satellite - Platforma HD Ltd."
      },
      { 0x1715 ,  0x1715,
        "Eutelsat W4 at 36 E - Satellite - Tricolor TV"
      },
      { 0x1716 ,  0x1716,
        "Skyway USA - Satellite - Skyway USA, LLC."
      },
      { 0x1717 ,  0x1717,
        "France Telecom Orange - Satellite - France Telecom Orange"
      },
      { 0x2000 ,  0x2000,
        "Thiacom 1 & 2 co-located 78.5°E - Satellite - Shinawatra Satellite"
      },
      { 0x2001 ,  0x2002,
        "Osaka Yusen Terrestrial A - B - Terrestrial - StarGuide Digital Networks"
      },
      { 0x2003 ,  0x2003,
        "KPN - Terrestrial - KPN Broadcast Services"
      },
      { 0x2004 ,  0x2004,
        "MiTV Networks Broadcast Terrestrial Network - DVB-H - Terrestrial - MiTV Networks Sdn Bhd Malaysia"
      },
      { 0x2005 ,  0x2005,
        "PT MAC - Terrestrial - PT. Mediatama Anugrah Citra"
      },
      { 0x2006 ,  0x2006,
        "Dominanta DVB-H Service - Terrestrial - Dominanta LLC"
      },
      { 0x2007 ,  0x2007,
        "DVB-H Austria - Terrestrial - Media Broadcast GmbH"
      },
      { 0x2008 ,  0x2008,
        "Levira Mobile TV - Terrestrial - Levira AS"
      },
      { 0x2009 ,  0x2009,
        "Mobision - Terrestrial - Alsumaria TV"
      },
      { 0x200A ,  0x200A,
        "Trenmobile - Terrestrial - PT. Citra Karya Investasi"
      },
      { 0x200B ,  0x200B,
        "VTC Mobile TV - Terrestrial - VTC Mobile TV"
      },
      { 0x200C ,  0x200C,
        "RMN Network - Terrestrial - Radio Mindanao Network Inc."
      },
      { 0x200D ,  0x200D,
        "Sudatel Mobile TV - Terrestrial - Sudatel"
      },
      { 0x200E ,  0x200F,
        "Vovinet Entertainment Private Limited - Cable - Vovinet Entertainment Private Limited"
      },
      { 0x20FA ,  0x20FA,
        "French Digital Terrestrial Television - Terrestrial - Conseil Supérier de l'Audiovisuel (CSA)"
      },
      { 0x2A00 ,  0x2A00,
        "  Kentavr DVB-H Network - Terrestrial - Kentavr"
      },
      { 0x2B00 ,  0x2B00,
        "DTT – Sky New Zealand - Terrestrial - Sky Network Television Limited"
      },
      { 0x3000 ,  0x3000,
        "PanAmSat 4 68.5°E - Satellite - Pan American Satellite System"
      },
      { 0x3001 ,  0x3100,
        "DTT Seychelles - Terrestrial - Seychelles Broadcasting Corporation"
      },
      { 0x3001 ,  0x3100,
        "DTT Serbia - JP Emisiona Tehnika i Veze - Terrestrial - DTT Serbia - JP Emisiona Tehnika i Veze"
      },
      { 0x3001 ,  0x3100,
        "German Digital Terrestrial Television - Terrestrial - IRT on behalf of the German DVB-T broadcasts"
      },
      { 0x3001 ,  0x3100,
        "Gibraltar Regulatory Authority - Terrestrial - Gibraltar Regulatory Authority"
      },
      { 0x3001 ,  0x3100,
        "DTT - Latvian Digital Terrestrial Television - Terrestrial - SIA Lattelecom"
      },
      { 0x3101 ,  0x3100,
        "Communications Regulatory Authority of Namibia (CRAN) - Terrestrial - Communications Regulatory Authority of Namibia (CRAN)"
      },
      { 0x3001 ,  0x3100,
        "Italian Digital Terrestrial Television - Terrestrial - Italian Telecommunications Ministry"
      },
      { 0x3001 ,  0x3100,
        "DTT - Slovak Republic (provisional) - To be defined - "
      },
      { 0x3001 ,  0x3100,
        "Ghana DTT - Terrestrial - Ghana National Communications Authority"
      },
      { 0x3001 ,  0x3100,
        "UK Digital Terrestrial Television - Terrestrial - Independant Television Comission"
      },
      { 0x3001 ,  0x3100,
        "DTT - South African Digital Terrestrial Television - Terrestrial - South African Broadcasting Corporation Ltd. (SABC), pending formation of 'DZONGA'"
      },
      { 0x3101 ,  0x3101,
        "ABS-CBN - Terrestrial - ABS-CBN Broadcasting Corporation"
      },
      { 0x3102 ,  0x3102,
        "AMCARA Broadcasting Network - Terrestrial - ABS-CBN Broadcasting Corporation"
      },
      { 0x3101 ,  0x3200,
        "HACA - Terrestrial - HACA"
      },
      { 0x3101 ,  0x3200,
        "DTT Country of Curacao - Terrestrial - Bureau Telecommunicatie en Post"
      },
      { 0x3101 ,  0x3200,
        "Swedish Digital Terrestrial Television - Terrestrial - Post och Telestyrelsen"
      },
      { 0x3101 ,  0x3200,
        "Office of National Broadcasting and Telecommunications Commission - Terrestrial - Office of National Broadcasting and Telecommunications Commission"
      },
      { 0x3101 ,  0x3200,
        "Czech Republic Digital Terrestrial Television - Terrestrial - Czech Digital Group"
      },
      { 0x3103 ,  0x3200,
        "DTT - Philippines Digital Terrestrial Television - Terrestrial - NTA (pending - ABS-CBN in meantime)"
      },
      { 0x3101 ,  0x3200,
        "US Digital Terrestrial Television - Terrestrial - BellSouth Entertainment, Atlanta, GA, USA (on behalf of US broadcasters)"
      },
      { 0x3101 ,  0x3200,
        "DTT - Croatia (provisional) - Terrestrial - "
      },
      { 0x3101 ,  0x3200,
        "Croatian Post and Electronic Communications Agency (HAKOM) - Terrestrial - Croatian Post and Electronic Communications Agency (HAKOM)"
      },
      { 0x3101 ,  0x3200,
        "Spanish Digital Terrestrial Television - Terrestrial - CMT (Spanish Regulstor"
      },
      { 0x3101 ,  0x3200,
        "Netherlands Digital Terrestrial Television - Terrestrial - Nozema"
      },
      { 0x3201 ,  0x3210,
        "Singapore Digital Terrestrial Television - Terrestrial - Singapore Broadcasting Authority"
      },
      { 0x3211 ,  0x3211,
        "MediaCorp - Terrestrial - MediaCorp Ltd."
      },
      { 0x3212 ,  0x3212,
        "StarHub Cable Vision - Cable - StarHub Cable Vision Ltd."
      },
      { 0x3201 ,  0x3300,
        "Australian Digital terrestrial Television - Terrestrial - Australian Broadcasting Authority"
      },
      { 0x3201 ,  0x3300,
        "Danish Digital Terrestrial Television - Terrestrial - National Telecom Agency Denmark"
      },
      { 0x3201 ,  0x3300,
        "DTT - Slovenian Digital Terrestrial Television - Terrestrial - APEK"
      },
      { 0x3201 ,  0x3300,
        "Irish Digital terrestrial Television - Terrestrial - Irish OFCOM"
      },
      { 0x3201 ,  0x3300,
        "Estonian Digital Terrestrial Television - Terrestrial - Estonian Terrestrial Regulator"
      },
      { 0x3201 ,  0x3300,
        "DTT - Andorran Digital Terrestrial Television - Terrestrial - STA"
      },
      { 0x3213 ,  0x3300,
        "Singapore Digital Terrestrial Television - Terrestrial - Singapore Broadcasting Authority"
      },
      { 0x3201 ,  0x3300,
        "Swiss Digital Terrestrial Television - Terrestrial - BAKOM"
      },
      { 0x3201 ,  0x3300,
        "DTT - Romania (provisional) - Terrestrial - "
      },
      { 0x3301 ,  0x3400,
        "Iceland DTT - - - Vodafone Iceland "
      },
      { 0x3301 ,  0x3400,
        "Autoridad Nacional de los Servicios Públicos - Terrestrial - Autoridad Nacional de los Servicios Públicos"
      },
      { 0x3301 ,  0x3400,
        "Israeli Digital Terrestrial Television - Terrestrial - BEZEQ (The Israel Telecommunication Corp Ltd.)"
      },
      { 0x3301 ,  0x3400,
        "Taiwanese Digital Terrestrial Television - Terrestrial - Directorate General of Telecommunications"
      },
      { 0x3301 ,  0x3400,
        "Myanmar DTT - Terrestrial - Myanma Radio and Television"
      },
      { 0x3301 ,  0x3400,
        "Finnish Digital Terrestrial Television - Terrestrial - Telecommunicatoins Administratoin Centre, Finland"
      },
      { 0x3301 ,  0x3400,
        "Austrian Digital Terrestrial Television - Terrestrial - ORS"
      },
      { 0x3301 ,  0x3400,
        "French Digital Terrestrial Television - Terrestrial - Conseil Superieur de l'AudioVisuel"
      },
      { 0x3301 ,  0x3400,
        "DTT - Ukraine (provisional) - Terrestrial - "
      },
      { 0x3301 ,  0x3400,
        "DTT Lithuania - Terrestrial - Communications Regulatory Authority"
      },
      { 0x3301 ,  0x3400,
        "Malaysian Technical Standards Forum Bhd (MTFSB) - Terrestrial - Malaysian Technical Standards Forum Bhd (MTFSB)"
      },
      { 0x3401 ,  0x3500,
        "Belgian Digital Terrestrial Television - Terrestrial - "
      },
      { 0x3401 ,  0x3500,
        "DTT- Portugal - Terrestrial - ANACOM- National Communications Authority"
      },
      { 0x3401 ,  0x3500,
        "Norwegian Digital Terrestrial Television - Terrestrial - "
      },
      { 0x3401 ,  0x3500,
        "DTT- Hungarian Digital Terrestrial Television - Terrestrial - National Communications Authority, Hungary "
      },
      { 0x3401 ,  0x3500,
        "DTT - New Zealand Digital Terrestrial Television - Terrestrial - TVNZ on behalf of Freeview (New Zealand)"
      },
      { 0x3401 ,  0x3500,
        "DTT- Poland - Terrestrial - Office of Electronic Communications"
      },
      { 0x3501 ,  0x3600,
        "DTT - Russian Federation - Terrestrial - RTRN"
      },
      { 0xA510 ,  0x589,
        "Telefonica Cable - Cable - Telefonica Cable SA"
      },
      { 0xA001 ,  0xA001,
        "RRD - Terrestrial - RRD Reti Radiotelevisive Digitali Spa"
      },
      { 0xA001 ,  0xA001,
        "H3G - Terrestrial - 3lettronica Industriale S.p.A"
      },
      { 0xA010 ,  0xA010,
        "Foxtel Cable - Cable - Foxtel (Australia)"
      },
      { 0xA011 ,  0xA011,
        "Sichuan Cable TV Network - Cable - Sichuan Cable TV Network"
      },
      { 0xA012 ,  0xA012,
        "CNS - Cable - STAR Koos Finance Company (Taiwan)"
      },
      { 0xA013 ,  0xA013,
        "Versatel - Cable - Versatel"
      },
      { 0xA014 ,  0xA014,
        "New Vision Wave - Cable - SKFC (Taiwan)"
      },
      { 0xA015 ,  0xA015,
        "Prosperity - Cable - SKFC (Taiwan)"
      },
      { 0xA016 ,  0xA016,
        "Shin Ho Ho (SHH) - Cable - SKFC (Taiwan)"
      },
      { 0xA017 ,  0xA017,
        "Gaho - Cable - SKFC (Taiwan)"
      },
      { 0xA018 ,  0xA018,
        "Wonderful - Cable - SKFC (Taiwan)"
      },
      { 0xA019 ,  0xA019,
        "Everlasting - Cable - SKFC (Taiwan)"
      },
      { 0xA01A ,  0xA01A,
        "Telefirst - Cable - SKFC (Taiwan)"
      },
      { 0xA01B ,  0xA01B,
        "Suncrown - Cable - SKFC (Taiwan)"
      },
      { 0xA01C ,  0xA01C,
        "Twin Star - Cable - SKFC (Taiwan)"
      },
      { 0xA01D ,  0xA01D,
        "Shing Lian - Cable - SKFC (Taiwan)"
      },
      { 0xA01E ,  0xA01E,
        "Clearvision - Cable - SKFC (Taiwan)"
      },
      { 0xA01F ,  0xA01F,
        "DAWS - Cable - SKFC (Taiwan)"
      },
      { 0xA020 ,  0xA020,
        "Chongqing - Cable - Chongqing (PRC)"
      },
      { 0xA021 ,  0xA021,
        "Guizhou - Cable - Guizhou (PRC)"
      },
      { 0xA022 ,  0xA022,
        "Hathway - Cable - Hathway (India)"
      },
      { 0xA023 ,  0xA02C,
        "RCN  1 - 10 - Cable - Rogers Cable (USA)"
      },
      { 0xA02D ,  0xA040,
        "(NDS services) - Cable - (NDS to be allocated)"
      },
      { 0XA040 ,  0XA040,
        "COMCOR-TV - Cable - COMCOR-TV"
      },
      { 0xA041 ,  0xA043,
        "Euskaltel TV On Line - Cable - Euskaltel"
      },
      { 0xA044 ,  0xA044,
        "Primacom - Cable - Primacom A.G"
      },
      { 0xA045 ,  0xA045,
        "Hong Kong CABLE TV - Cable & MMDS - Hong Kong Cable Television Limited"
      },
      { 0xA046 ,  0xA046,
        "Regional Cable Network - Cable - Wilhelm.Tel"
      },
      { 0xA050 ,  0xA070,
        "Cable & Wireless Optus - Cable - Cable & Wireless Optus"
      },
      { 0xA050 ,  0xA070,
        "Cable & Wireless Communications - Cable - Cable & Wireless Communications"
      },
      { 0xA070 ,  0xA070,
        "ewt Network - Cable - ewt gmbh"
      },
      { 0xA071 ,  0xA071,
        "Värnamo Energi AB - Cable - Värnamo Energi AB"
      },
      { 0xA08C ,  0xA09B,
        "Telenor Cable TV - Cable - Telenor Broadcast Holding AS"
      },
      { 0xA12B ,  0xA12B,
        "Telstra Saturn Cable - Cable - TelstraSaturn Limited"
      },
      { 0xA001 ,  0xA400,
        "Tele Denmark - Cable - Tele Denmark"
      },
      { 0xA401 ,  0xA401,
        "ARD - Cable - ARD-Sternpunkte"
      },
      { 0xA509 ,  0xA509,
        "Welho Cable Network Helsinki - Cable - Welho"
      },
      { 0xA510 ,  0xA510,
        "NOB - Cable - Dutch Broadcast Facilities (NOB)"
      },
      { 0xA511 ,  0xA511,
        "Martens Multimedia - Cable Networks - Cable - Martens Antennen- und Kabelanlagen Gesellschaft mbH"
      },
      { 0xA512 ,  0xA512,
        "LIVAS Telecommunications Group - Cable - LIVAS Telecom Cable"
      },
      { 0xA513 ,  0xA513,
        "Hathway - Cable - Hathway Cable & Datacom Pvt Ltd"
      },
      { 0xA600 ,  0xA600,
        "Telstra HFC National Network - HFC - Telstra"
      },
      { 0xA600 ,  0xA600,
        "Madritel - Cable - Madritel ( Spain ) (NDS)"
      },
      { 0xA602 ,  0xA602,
        "Tevel - Cable - Tevel Cabe ( Israel ) (NDS)"
      },
      { 0xA603 ,  0xA603,
        "Globo Cabo - Cable - Globo Cabo ( Brazil ) (NDS)"
      },
      { 0xA604 ,  0xA604,
        "Cablemas - Cable - Cablemas ( Mexico ) (NDS)"
      },
      { 0xA605 ,  0xA605,
        "Information Network Centre (INC) - Cable - Information Network Centre ( China ) - SARFT (NDS)"
      },
      { 0xA601 ,  0xA615,
        "Rhône Vision Cable - Cable - Rhône Vision Cable"
      },
      { 0xA61F ,  0xA61F,
        "BellSouth Entertainment - Cable - BellSouth Entertainment, Atlanta, GA, USA"
      },
      { 0xA600 ,  0xA640,
        "Cable Services de France - Cable - Cable Service de France"
      },
      { 0xA641 ,  0xA660,
        "Dexys - Cable & MMDS - Dexys"
      },
      { 0xA661 ,  0xA663,
        "Est Video Communication - Cable - Video Communication"
      },
      { 0xA664 ,  0xA666,
        "Est Video Communication Haut-Rhin - Cable - Video Communication Haut-Rhin"
      },
      { 0xA670 ,  0xA68F,
        "SUDCABLE Services - Cable - SUDCABLE Services"
      },
      { 0xA697 ,  0xA69F,
        "OMNE Communications - Cable - OMNE Communications Ltd."
      },
      { 0xA700 ,  0xA700,
        "Madritel - Cable - Madritel Comunicaciones"
      },
      { 0xA701 ,  0xA701,
        "NTL Cable Network - Cable - NTL"
      },
      { 0xA720 ,  0xA720,
        "NSSLGlobal - Satellite - NSSLGlobal"
      },
      { 0xA750 ,  0xA750,
        "Telewest Communications Cable Network - Cable - Telewest Communications Plc"
      },
      { 0xA751 ,  0xA75F,
        "TVCabo - Cable - TV Cabo"
      },
      { 0xA800 ,  0xA8FF,
        "UPC Cable - Cable - UPC"
      },
      { 0xA900 ,  0xA900,
        "M-net Telekommunikations GmbH - Cable Networks - M-net Telekommunikations GmbH"
      },
      { 0xF001 ,  0xF01F,
        "Kabel Deutschland - Cable - Kabel Deutschland "
      },
      { 0xF020 ,  0xF020,
        "Deutsche Telekom AG - Cable - Deutsche Telekom AG"
      },
      { 0xF100 ,  0xF100,
        "Casema - Cable - Casema"
      },
      { 0xF101 ,  0xF101,
        "Bosch Telecom - Cable Networks - Cable - BOSCH Breitbandnetze"
      },
      { 0xF11F ,  0xF11F,
        "visAvision Cable Network - Cable - European Telecommunications Satellite Organization"
      },
      { 0xFBFC ,  0xFBFC,
        "MATAV - Cable - MATAV Israel (NDS)"
      },
      { 0xFBFD ,  0xFBFD,
        "Telia Kabel-TV - Cable Networks - Telia, Sweden"
      },
      { 0xFBFE ,  0xFBFE,
        "TPS - Cable Networks - la Télévision Par Satellite"
      },
      { 0xFBFF ,  0xFBFF,
        "Sky Italia - Satellite - Sky Italia SA."
      },
      { 0xFC00 ,  0xFCFF,
        "France Telecom Cable - Cable - France Telecom"
      },
      { 0xFD00 ,  0xFDFF,
        "National Cable Network - Cable - Lyonnaise Communications"
      },
      { 0xFF01 ,  0xFFFF,
        "Private_temporary_use - Not defined - User_defined"
      },