
      { 0x00000000 ,  0x00000000,
        "Reserved -  - "
      },
      { 0x00000001 ,  0x00000001,
        "SES -  - "
      },
      { 0x00000002 ,  0x00000004,
        "BskyB 1 - 3 -  - "
      },
      { 0x00000005 ,  0x00000005,
        "ARD, ZDF, ORF -  - "
      },
      { 0x00000006 ,  0x00000006,
        "Nokia Multimedia Network Terminals -  - "
      },
      { 0x00000007 ,  0x00000007,
        "AT Entertainment Ltd. -  - "
      },
      { 0x00000008 ,  0x00000008,
        "TV Cabo Portugal   -  - "
      },
      { 0x00000009 ,  0x0000000D,
        "Nagravision SA – Kudelski 1 - 5 -  - "
      },
      { 0x0000000E ,  0x0000000E,
        "Valvision SA   -  - "
      },
      { 0x0000000F ,  0x0000000F,
        "Quiero Televisión   -  - "
      },
      { 0x00000010 ,  0x00000010,
        "La Télévision Par Satellite (TPS) -  - "
      },
      { 0x00000011 ,  0x00000011,
        "Echostar Communications -  - "
      },
      { 0x00000012 ,  0x00000012,
        "Telia AB -  - "
      },
      { 0x00000013 ,  0x00000013,
        "Viasat   -  - "
      },
      { 0x00000014 ,  0x00000014,
        "Boxer TV Access -  - "
      },
      { 0x00000015 ,  0x00000015,
        "MediaKabel  -  - "
      },
      { 0x00000016 ,  0x00000016,
        "Casema   -  - "
      },
      { 0x00000017 ,  0x00000017,
        "Humax Electronics Co. Ltd . -  - "
      },
      { 0x00000018 ,  0x00000018,
        "Neotion SA -  - "
      },
      { 0x00000019 ,  0x00000019,
        "Singapore Digital Terrestrial Television   -  - "
      },
      { 0x0000001A ,  0x0000001A,
        "Télédiffusion de France (TDF) -  - "
      },
      { 0x0000001B ,  0x0000001B,
        "Intellibyte Inc. -  - "
      },
      { 0x0000001C ,  0x0000001C,
        "Digital Theater Systems Ltd -  - "
      },
      { 0x0000001D ,  0x0000001D,
        "Finlux Ltd. -  - "
      },
      { 0x0000001E ,  0x0000001E,
        "Sagem SA -  - "
      },
      { 0x0000001F ,  0x0000001F,
        "Beijing Compunicate Technology Inc -  - "
      },
      { 0x00000020 ,  0x00000023,
        "Lyonnaise Cable 1 - 4 -  - "
      },
      { 0x00000024 ,  0x00000024,
        "Metronic -  - "
      },
      { 0x00000025 ,  0x00000025,
        "MTV Europe  -  - "
      },
      { 0x00000026 ,  0x00000026,
        "Pansonic   -  - "
      },
      { 0x00000027 ,  0x00000027,
        "Mentor Data System, Inc . -  - "
      },
      { 0x00000028 ,  0x00000028,
        "EACEM   -  - "
      },
      { 0x00000029 ,  0x00000029,
        "NorDig   -  - "
      },
      { 0x0000002A ,  0x0000002A,
        "Intelsis Sistemas Inteligentes S.A . -  - "
      },
      { 0x0000002B ,  0x0000002B,
        "DTV haber ve Gorsel yayýncilik -  - "
      },
      { 0x0000002D ,  0x0000002D,
        "Alpha Digital Synthesis S.A. -  - "
      },
      { 0x0000002E ,  0x0000002E,
        "THOMSON -  - "
      },
      { 0x0000002F ,  0x0000002F,
        "Conax A.S. -  - "
      },
      { 0x00000030 ,  0x00000030,
        "Telenor -  - "
      },
      { 0x00000031 ,  0x00000031,
        "TeleDenmark  -  - "
      },
      { 0x00000032 ,  0x00000032,
        "Foxtel Management -  - "
      },
      { 0x00000033 ,  0x00000033,
        "InOutTV -  - "
      },
      { 0x00000034 ,  0x00000034,
        "InOutTV SA (2) -  - "
      },
      { 0x00000035 ,  0x00000035,
        "Europe Online Networks S.A . -  - "
      },
      { 0x00000036 ,  0x00000036,
        "Groupe Canal+ -  - "
      },
      { 0x00000037 ,  0x00000037,
        "FreeView (NZ) -  - "
      },
      { 0x00000038 ,  0x00000038,
        "OTE   -  - "
      },
      { 0x00000039 ,  0x00000039,
        "Telewizja Polsat   -  - "
      },
      { 0x0000003A ,  0x0000003A,
        "arena Sport Rechte und Marketing GmbH -  - "
      },
      { 0x0000003B ,  0x0000003B,
        "Wyplay SAS -  - "
      },
      { 0x0000003D ,  0x0000003D,
        "Interactive Technologies AD -  - "
      },
      { 0x0000003E ,  0x0000003E,
        "T-Kábel Magyarország Kft. -  - "
      },
      { 0x0000003F ,  0x0000003F,
        "ITI Neovision -  - "
      },
      { 0x00000040 ,  0x00000040,
        "CI Plus LLP -  - "
      },
      { 0x00000041 ,  0x00000041,
        "France Telecom Orange -  - "
      },
      { 0x00000050 ,  0x00000050,
        "Com Hem ab -  - "
      },
      { 0x000000A0 ,  0x000000A0,
        "Sentech   -  - "
      },
      { 0x000000A1 ,  0x000000A1,
        "TechniSat Digital GmbH   -  - "
      },
      { 0x000000A2 ,  0x000000A2,
        "LogiWays -  - "
      },
      { 0x000000A3 ,  0x000000A3,
        "EFG -  - "
      },
      { 0x000000A4 ,  0x000000A4,
        "CANAL OVERSEAS -  - "
      },
      { 0x000000A5 ,  0x000000A5,
        "Canal+ Cyfrowy -  - "
      },
      { 0x000000B0 ,  0x000000B0,
        "ITI Neovision Sp. z.o.o. -  - "
      },
      { 0x000000BE ,  0x000000BE,
        "BetaTechnik -  - "
      },
      { 0x000000C0 ,  0x000000C0,
        "NDS France -  - "
      },
      { 0x000000D0 ,  0x000000D0,
        "Dolby Laboratories Inc. -  - "
      },
      { 0x000000E0 ,  0x000000E0,
        "ExpressVu Inc. -  - "
      },
      { 0x000000F0 ,  0x000000F0,
        "France Telecom, CNES and DGA (STENTOR) -  - "
      },
      { 0x00000100 ,  0x00000100,
        "OpenTV -  - "
      },
      { 0x0000013F ,  0x0000013F,
        "Eutelsat S.A. (1) -  - "
      },
      { 0x00000140 ,  0x00000140,
        "Eltrona-Interdiffusion S.A. -  - "
      },
      { 0x00000150 ,  0x00000150,
        "Loewe Opta GmbH  -  - "
      },
      { 0x00000160 ,  0x00000160,
        "Triax A/S -  - "
      },
      { 0x00000170 ,  0x00000170,
        "Deutsche Telekom AG -  - "
      },
      { 0x00000180 ,  0x00000180,
        "EAB - Ericsson AB -  - "
      },
      { 0x00000190 ,  0x00000190,
        "Samsung Electronics (UK) Ltd -  - "
      },
      { 0x000001A0 ,  0x000001A0,
        "RCS&RDS -  - "
      },
      { 0x0000055F ,  0x0000055F,
        "Eutelsat S.A. (2) -  - "
      },
      { 0x00000600 ,  0x00000601,
        "UPC 1 - 2 -  - "
      },
      { 0x00000602 ,  0x00000603,
        "UPC Broadband Holding Services BV -  - "
      },
      { 0x00000A2B ,  0x00000A2B,
        "A2B Electronics AB -  - "
      },
      { 0x00000ACE ,  0x00000ACE,
        "Ortikon Interactive Oy -  - "
      },
      { 0x00000AD0 ,  0x00000AD0,
        "Zenterio AB -  - "
      },
      { 0x00001000 ,  0x00001000,
        "La Télévision Par Satellite (TPS ) -  - "
      },
      { 0x000010F0 ,  0x000010F0,
        "TP S.A. -  - "
      },
      { 0x00002000 ,  0x00002000,
        "UC-Connect -  - "
      },
      { 0x00002068 ,  0x00002068,
        "Myanma Radio and Television -  - "
      },
      { 0x000020AA ,  0x000020AA,
        "Comision Nacional de Television de Colombia -  - "
      },
      { 0x00002160 ,  0x00002160,
        "Vodafone Iceland -  - "
      },
      { 0x00002168 ,  0x00002168,
        "Ministry of Communication and Information Technology of the Republic of Indonesia -  - "
      },
      { 0x00002180 ,  0x00002180,
        "HACA -  - "
      },
      { 0x000021CA ,  0x000021CA,
        "Malaysian Technical Standards Forum Bhd (MTFSB) -  - "
      },
      { 0x00002213 ,  0x00002213,
        "Bureau Telecommunicatie en Post -  - "
      },
      { 0x0000224F ,  0x0000224F,
        "Autorida Nacional de los Servicios Publicos -  - "
      },
      { 0x00002268 ,  0x00002268,
        "Office of Electronic Communications -  - "
      },
      { 0x00002283 ,  0x00002283,
        "RTRN -  - "
      },
      { 0x000022B0 ,  0x000022B0,
        "JP Emisiona Tehnika i Veze -  - "
      },
      { 0x000022BF ,  0x000022BF,
        "Telecommunications office of the Slovak republic -  - "
      },
      { 0x000022C1 ,  0x000022C1,
        "DTT - Slovenia Digital Terrestrial Television -  - "
      },
      { 0x000022C6 ,  0x000022C6,
        "DTT - South African Digital Terrestrial Television -  - "
      },
      { 0x000022C7 ,  0x000022C7,
        "DTT- Hungarian Digital Terrestrial Television -  - "
      },
      { 0x000022C8 ,  0x000022C8,
        "SIA Lattelecom -  - "
      },
      { 0x000022CE ,  0x000022CE,
        "DTT - Irish Digital Terrestrial Television -  - "
      },
      { 0x000022CF ,  0x000022CF,
        "DTT- Portugal Digital Terrestrial Television -  - "
      },
      { 0x000022D4 ,  0x000022D4,
        "“Spanish Broadcasting Regulator  -  - "
      },
      { 0x000022F1 ,  0x000022F1,
        "“Swedish Broadcasting Regulator ” -  - "
      },
      { 0x000022FC ,  0x000022FC,
        "Office of National Broadcasting and Telecommunications Commission -  - "
      },
      { 0x0000233A ,  0x0000233A,
        "Independent Television Commission  -  - "
      },
      { 0x00002B00 ,  0x00002B00,
        "Sky Network Television Limited -  - "
      },
      { 0x00003200 ,  0x0000320F,
        "(Australian Terrestrial Television Networks) -  - "
      },
      { 0x0000333A ,  0x0000333A,
        "Digital TV Group -  - "
      },
      { 0x00006000 ,  0x00006000,
        "News Datacom -  - "
      },
      { 0x00006001 ,  0x00006006,
        "NDC 1 - 6 -  - "
      },
      { 0x00362275 ,  0x00362275,
        "Irdeto -  - "
      },
      { 0x004E544C ,  0x004E544C,
        "NTL -  - "
      },
      { 0x00532D41 ,  0x00532D41,
        "Scientific Atlanta -  - "
      },
      { 0x00564F4F ,  0x00564F4F,
        "VOO (Tecteo) -  - "
      },
      { 0x00600000 ,  0x00600000,
        "Rhône Vision Cable -  - "
      },
      { 0x41555300 ,  0x41555300,
        "Foxtel Management -  - "
      },
      { 0x44414E59 ,  0x44414E59,
        "News Datacom (IL) 1 -  - "
      },
      { 0x46524549 ,  0x46524549,
        "News Datacom (IL) 1 -  - "
      },
      { 0x46534154 ,  0x46534154,
        "BBC -  - "
      },
      { 0x46536174 ,  0x46536174,
        "BBC -  - "
      },
      { 0x46545600 ,  0x46545620,
        "FreeTV 1 - 33 -  - "
      },
      { 0x46585431 ,  0x46585433,
        "FOXTEL Management Pty Ltd -  - "
      },
      { 0x4658544C ,  0x4658544C,
        "FOXTEL Management Pty Ltd -  - "
      },
      { 0x4A4F4A4F ,  0x4A4F4A4F,
        "Kabel Deutschland -  - "
      },
      { 0x4F545600 ,  0x4F5456FF,
        "(OpenTV 1 - 256) -  - "
      },
      { 0x50484900 ,  0x504849FF,
        "(Philips DVS 1 - 256) -  - "
      },
      { 0x53415053 ,  0x53415053,
        "Scientific Atlanta -  - "
      },
      { 0x5347444E ,  0x5347444E,
        "StarGuide Digital Networks  -  - "
      },
      { 0x53475255 ,  0x53475255,
        "GkWare e.K. -  - "
      },
      { 0x56444700 ,  0x56444700,
        "Vía Digital -  - "
      },
      { 0x564F564F ,  0x564F564F,
        "TechnoTrend AG -  - "
      },
      { 0xBBBBBBBB ,  0xBBBBBBBB,
        "Bertelsmann Broadband Group   -  - "
      },
      { 0xE0E0E0E0 ,  0xE0E0E0E0,
        "eventIS -  - "
      },
      { 0xECCA0001 ,  0xECCA0001,
        "ECCA (European Cable Communications Association ) -  - "
      },
      { 0xFCFCFCFC ,  0xFCFCFCFC,
        "France Telecom -  - "
      },